### PR TITLE
Added UberNES Screensaver

### PR DESCRIPTION
**Pull request by renesansz**

### CODE REVIEW

**Comment by aharris88** [comment]
I tried out this screensaver, but I couldn't get it to work. I downloaded some videos and set the movie path. I didn't have any roms, but I tried downloading one and setting that path. When I ran the screensaver, it said it couldn't find any nes movies.

Sorry, this screensaver seems pretty awesome, but it seems like it's too hard to set up. I'm going to close this issue. But if you can provide some more insight into how to get it to work, or why it's awesome, I'll reconsider it in the future.

**Comment by renesansz** [comment]
@aharris88 it's okay, I apologise that it didn't work for you, for the roms I've used this one [link](https://kat.cr/nes-nintendo-games-collection-1029-roms-fceux-2-2-0-t6968178.html), just to make sure all NES games will be detected.

The rest of the instruction can be found [here](http://www.ubernes.com/nesscreensaverinstall.html).

A screenshot of your screensaver setting would also be great, I might able to help you out easily.
Thanks

**Comment by aharris88** [comment]
That first link doesn't work.

**Comment by renesansz** [comment]
Oh, I see, it works fine for me.
Anyways, how about this [one](https://kat.cr/8820-nes-roms-t429318.html)?

**Pull request closed without merging**
