### PR TITLE
Improve contribution guidelines

### PR DESCRIPTION
**Pull request by mischah**
* Correct format description of contributions
* Move description how to get screenshots to contribution guidelines

### CODE REVIEW

**Comment by aharris88** [comment]
Good idea. Could you also remove How to get screenshots from the Table of Contents?

**Comment by mischah** [comment]
Oops. Done :blush:

**Comment by aharris88** [comment]
Looks like you have conflicts now that I merged your other pull request.

**Comment by mischah** [comment]
Ah. Hang on a second …

**Comment by mischah** [comment]
You should be able to merge now.

**Pull request merged**
